namespace: example-app-prod
resources:
- ./../../base
images:
- name: app-image
  newName: ghcr.io/cringdahl/example-app
  newTag: 2.6.2
commonLabels:
  app.kubernetes.io/instance: example-app-prod
# patchesJson6902:
# - patch: |-
#     - op: replace
#       path: /spec/template/spec/imagePullSecrets/0/name
#       value: example-app-ghcrcred
#   target:
#     group: apps
#     kind: Deployment
#     name: deployment
#     version: v1
# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
