namespace: example-app-prod
resources:
- ./../../base
images:
- name: app-image
  newName: ghcr.io/cringdahl/example-app
  newTag: v1
commonLabels:
  app.kubernetes.io/instance: example-app-prod
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
