namespace: example-app-pr-1
nameSuffix: -pr-1-e719437
resources:
- ./../../base
images:
- name: app-image
  newName: ghcr.io/cringdahl/example-app
  newTag: pr-1-e719437
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/instance: example-app-pr-1-e719437
patches:
- path: ingress-patch.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: ingress
    version: v1
