namespace: example-app-pr-2
nameSuffix: -pr-2-284b2fa
resources:
- ./../../base
  #newName: harbor.10-22-37-98.sslip.io/example/app
images:
- name: app-image
  newName: ghcr.io/cringdahl/example-app
  newTag: pr-2-284b2fa
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/instance: example-app-pr-2-284b2fa
patches:
- path: ingress-patch.yaml
  target:
    group: networking.k8s.io
    kind: Ingress
    name: ingress
    version: v1
