apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: example-app-
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - sealedsecret.yaml
commonLabels:
  app.kubernetes.io/component: app
  app.kubernetes.io/name: example-app
  app.kubernetes.io/part-of: gitops-demo
configurations:
  - sealed-secret-config.yaml