nameReference:
- kind: SealedSecret # take our own generated name
  fieldSpecs:
  - kind: SealedSecret # and apply it to the template name, ie the unsealed Secret
    path: spec/template/metadata/name
  - kind: Deployment
    path: /spec/template/spec/imagePullSecrets/name