name: Close Manifest Pull Request

on:
  workflow_dispatch:
    inputs:
      actor:
        type: string
        required: true
        description: Username that created application repo PR
      head_pr:
        type: string
        required: true
        description: The number of the triggering application repo PR
      merged:
        type: boolean
        required: true
        description: True if closure is also a merge

jobs:
  close-pr:
    runs-on: ubuntu-latest
    # runs-on: internal-runner

    steps:
      # Checkout the source code in the repository
      - uses: actions/checkout@v4
    
      - name: Set 'branch' as manifest branch name (ie, pr-25 )
        id: branch
        run: echo "branch=pr-${{ github.event.inputs.head_pr }}" >> $GITHUB_OUTPUT
  
      - name: Close PR without merge
        if: github.event.inputs.merged == 'false'
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh pr close ${{ steps.branch.outputs.branch }} --delete-branch --comment "Closing PR and deleting branch due to lack of application PR merge"

      - name: Close PR with merge
        if: github.event.inputs.merged == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh pr merge ${{ steps.branch.outputs.branch }} --auto --delete-branch --squash
